### ISSUE TITLE
Unable to create GitHub milestones

### ISSUE THREAD

**Issue by tmillross** [LU-CML/activity-browser#15]
As part of research for creating the poster as documented here, I've been reading through all the issues on the AB master repo. [One of them](https://github.com/LCA-ActivityBrowser/activity-browser/issues/40) suggests improving our processes for versionining, changelog and milestones.
On attempting to [create a milestone](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) [on this page](https://github.com/LCA-ActivityBrowser/activity-browser/milestones) for our ongoing data-editing work, I'm unable to as the option is not available. I assume that enabling this would require a permissions change within our LU-CML organisation.

**Comment by marc-vdm** [comment]
Closing as outdated
